### ISSUE TITLE
New Resource Request

### ISSUE THREAD

**Issue by kievsash** [jsonberry/pentacle#155]
# Fill out these attributes
Cost: paid
Difficulty: beginner
Format: watch
Origin: "Good RxJS starter. Beginner-advanced level"
Title: Hands-On RxJS for Web Development
URL: https://www.packtpub.com/web-development/hands-rxjs-web-development-video

# Summary
Good RxJS starter with clear explanations. Oriented on total RxJS beginners but contains advanced level staff as well.
My video-course)

**Comment by jsonberry** [comment]
Thanks @kievsash! Sorry it took a little bit to get posted, it's up now: https://pentacledev.com/resources/hands-on-rxjs-for-web-development

**Comment by kievsash** [comment]
No worries, thank you!
