### ISSUE TITLE
New Resource Request

### ISSUE THREAD

**Issue by kievsash** [jsonberry/pentacle#159]
# Fill out these attributes
Cost: free 
Difficulty: intermediate-advanced
Format: watch
Origin: "Tools for RxJS code unit testing in Angular" by https://twitter.com/El_Extremal
Title: RxJS unit testing in Angular application. The whole picture.
URL: https://mailchi.mp/9c8299ec62c2/rxjsunittesting

# Summary
HERE YOU WILL LEARN:

Jasmine with done callback
VirtualTimeScheduler testing
fakeAsync testing
TestScheduler
TestScheduler.run methods
Marble testing
Jasmine-mables
rxjs-marbles
 
All examples code will be provided as Angular demo project in a GitHub repo!

**Comment by jsonberry** [comment]
Hey @kievsash! I archived the pentacle project and moved to a lean version over at https://learnreactive.com

Your other resource is already up there, and this one can be put up too. Can you add it as an issue here please? https://github.com/jsonberry/learn-reactive/issues/new?assignees=jsonberry&labels=resources&template=new_resource.md&title=New+Resource+Request

I'll add some stuff to this repo to make it more apparent that it's archived and the new stuff is at learn reactive, thanks!
