### ISSUE TITLE
Examples state

### ISSUE THREAD

**Issue by Fallenstedt** [jsonberry/pentacle#47]
How will ngrx scale as more examples are added? 

The toast lib adds its own state to ngrx when loaded. When I need to access the store from my `toast.facade`, is the store being injected the _entire_ ngrx store, or should it only reference my `ToastState` or `State` from pentacle/models

```typescript
export class ToastFacade {
  constructor(store: Store<ToastState>) {} //ToastState or State? 
}
```

I'm thinking it would be the State from `'@pentacle/models';`. Knowing this, should we create an examples feature reducer that consumes all example reducers? Can those sub-reducers be treated as entities?

Our store would look something like this:

```
{
  router: { ... },
  posts: {...},
  pages: {...},
  tags: {...},
  examples: {
     toast: { // toast-state go here ...},
     retry_with_backoff: { // retry-with-backoff-state go here ...},
     foo: { // foo-state go here ...}
  }
}
```
So for every module that's loaded, the example reducer grows with new entities. 

Is this the approach you were thinking? I'm thinking this would mimic the pages reducer.

**Comment by Fallenstedt** [comment]
Is it ok to create a big soup? So each example lib would be added at the root level:
```
{
  router: { ... },
  posts: {...},
  pages: {...},
  tags: {...},
  toast: { // toast-state go here ...},
  retry_with_backoff: { // retry-with-backoff-state go here ...},
  foo: { // foo-state go here ...}
}
```

**Comment by jsonberry** [comment]
I don't mind that for right now - I think we should work toward your idea, but I would just want to ensure lazy loading could be kept intact.

I've ran into this challenge before and didn't have time to solve it, so Pentacle will give us a good chance to come up with a strategy for this situation.
